# Generated by Django 5.1.7 on 2025-03-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('has_been_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('testimonial', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-graduation_date'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_completed']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', '-proficiency_level']},
        ),
        migrations.RenameField(
            model_name='education',
            old_name='field',
            new_name='field_of_study',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='position',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='live_url',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='current',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='technology_used',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='projects/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main_app.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
