# Generated by Django 5.1.7 on 2025-03-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contactmessage_testimonial_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
