# Generated by Django 5.1.7 on 2025-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_project_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('award', 'Award'), ('certification', 'Certification'), ('recognition', 'Recognition'), ('publication', 'Publication')], default='award', max_length=20)),
                ('organization', models.CharField(max_length=200)),
                ('date_received', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('link', models.URLField(blank=True, help_text='Link to certificate or award details', null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
    ]
