# Generated by Django 5.1.7 on 2025-03-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, default='BACKEND', max_length=100, null=True),
        ),
    ]
