# Generated by Django 5.1.7 on 2025-03-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('DATABASE', 'Database'), ('TOOLS', 'Tools'), ('VERSION_CONTROL', 'Version'), ('LIBRARIES', 'Library'), ('OTHER_TOOLS', 'Other')], default='BACKEND', max_length=100),
        ),
    ]
